# Site settings
title: The Mindful Programmer
email: hello@mindprog.com
description: > # this means to ignore newlines until "baseurl:"
  Teaching to develop mindfulness with programming exercises like coding dojos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thorbenegberts.github.io/mindprog-website/" # the base hostname & protocol for your site // http://mindprog.com
twitter_username: mindfulprogrammer
github_username:  thorbenegberts

# Build settings
markdown: kramdown
